export enum VisaType {
  VISA_FREE = "VISA_FREE",
  VISA_ON_ARRIVAL = "VISA_ON_ARRIVAL",
  EVISA = "EVISA",
  ETA = "ETA",
  VISA_REQUIRED = "VISA_REQUIRED",
  ADMISSION_REFUSED = "ADMISSION_REFUSED",
  VISA_WAIVER = "VISA_WAIVER",
  UNKNOWN = "UNKNOWN",
}
